// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiFutbolistas;

#nullable disable

namespace WebApiFutbolistas.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220306223349_Equipos")]
    partial class Equipos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.1.22076.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApiFutbolistas.Entidades.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Division")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FutbolistaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FutbolistaId");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("WebApiFutbolistas.Entidades.Futbolista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Futbolistas");
                });

            modelBuilder.Entity("WebApiFutbolistas.Entidades.Equipo", b =>
                {
                    b.HasOne("WebApiFutbolistas.Entidades.Futbolista", "Futbolista")
                        .WithMany("equipos")
                        .HasForeignKey("FutbolistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Futbolista");
                });

            modelBuilder.Entity("WebApiFutbolistas.Entidades.Futbolista", b =>
                {
                    b.Navigation("equipos");
                });
#pragma warning restore 612, 618
        }
    }
}
